blank_issues_enabled: true
contact_links:
  - name: Open edX Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Security report policy
    url: https://github.com/eduNEXT/openedx-events-2-zapier#reporting-security-issues
    about: Follow this policy to report security issues.
